# Generated by Django 5.2.9 on 2025-12-11 16:35

import apps.trailer.models
import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('sight', 'Sight'), ('van', 'Van'), ('snowblower', 'Snowblower'), ('lawnmower', 'Lawnmower')], max_length=50, verbose_name='Type')),
                ('subtype', models.CharField(blank=True, choices=[('onboard', 'Onboard'), ('closed', 'Closed')], max_length=50, null=True, verbose_name='Subtype')),
                ('brand_model', models.CharField(max_length=255, verbose_name='Brand and Model')),
                ('vin', models.CharField(max_length=100, unique=True, verbose_name='VIN Number')),
                ('license_plate', models.CharField(blank=True, max_length=50, verbose_name='License Plate')),
                ('photos', models.JSONField(default=list, verbose_name='Photos')),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('written_off', 'Written Off')], default='available', max_length=50, verbose_name='Status')),
                ('current_location', models.TextField(verbose_name='Current Location')),
                ('movement_history', models.JSONField(default=list, verbose_name='Movement History')),
                ('rental_service_history', models.JSONField(default=list, verbose_name='Rental/Service History')),
                ('mileage_motohours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mileage/Motohours')),
                ('documents', models.JSONField(default=list, verbose_name='Documents')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrailerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('icon', models.ImageField(blank=True, help_text='Format: PNG, size: 512*512 px', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), django.core.validators.validate_image_file_extension], verbose_name='Icon')),
                ('status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('del', 'Del')], default='yes', max_length=3, verbose_name='Activity status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Trailer category',
                'verbose_name_plural': 'Trailer categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrailerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('minimum_license', models.CharField(max_length=5, verbose_name='Minimum licence')),
                ('brutto', models.PositiveSmallIntegerField(default=0, verbose_name='Brutto')),
                ('netto', models.PositiveSmallIntegerField(default=0, verbose_name='Netto')),
                ('pins', models.PositiveSmallIntegerField(default=7, verbose_name='Pins')),
                ('sizes', models.CharField(max_length=50, verbose_name='Sizes')),
                ('main_image', models.ImageField(help_text='Format: .PNG, size: 1980 * 1280 px', upload_to=apps.trailer.models.TrailerType.trailer_type_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), django.core.validators.validate_image_file_extension], verbose_name='Image')),
                ('icon', models.ImageField(help_text='Format: .PNG, size: 512 * 512 px', upload_to=apps.trailer.models.TrailerType.trailer_type_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), django.core.validators.validate_image_file_extension], verbose_name='Icon')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('del', 'Del')], default='yes', max_length=3, verbose_name='Activity status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailer.trailercategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Trailer type',
                'verbose_name_plural': 'Trailer types',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrailerTypePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hour', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='For hour')),
                ('one_day', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='For one day')),
                ('two_days', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='For two days')),
                ('three_days', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='For three days')),
                ('week', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='For week')),
                ('month', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='For month')),
                ('trailer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='trailer.trailertype', verbose_name='Trailer type')),
            ],
            options={
                'verbose_name': 'Trailer type price',
                'verbose_name_plural': 'Trailer type prices',
            },
        ),
        migrations.CreateModel(
            name='TrailerTypeSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('trailer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='trailer.trailertype', verbose_name='Trailer type')),
            ],
            options={
                'verbose_name': 'Trailer type SEO',
                'verbose_name_plural': 'Trailer type SEO',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrailerCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='trailer.trailercategory')),
            ],
            options={
                'verbose_name': 'Trailer category Translation',
                'db_table': 'trailer_trailercategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrailerTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Number')),
                ('image', models.ImageField(help_text='Format: .PNG, size: 1980 * 1280 px', upload_to=apps.trailer.models.TrailerTypeImage.trailer_type_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), django.core.validators.validate_image_file_extension], verbose_name='Image')),
                ('trailer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trailer.trailertype', verbose_name='Trailer type')),
            ],
            options={
                'verbose_name': 'Trailer type image',
                'verbose_name_plural': 'Trailer type images',
                'unique_together': {('trailer_type', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TrailerTypeSEOTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('url', models.SlugField(blank=True, null=True, verbose_name='URL')),
                ('img', models.ImageField(blank=True, help_text='Format: PNG, size: 512*512 px', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), django.core.validators.validate_image_file_extension], verbose_name='Image')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='trailer.trailertypeseo')),
            ],
            options={
                'verbose_name': 'Trailer type SEO Translation',
                'db_table': 'trailer_trailertypeseo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TrailerTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('subtext', models.TextField(verbose_name='Sub text')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='trailer.trailertype')),
            ],
            options={
                'verbose_name': 'Trailer type Translation',
                'db_table': 'trailer_trailertype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
