# Generated by Django 5.2.9 on 2025-12-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailertypetranslation',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
        ),
    ]
