# Generated by Django 5.2.9 on 2025-12-11 16:35

import apps.user.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        ('employer', '0001_initial'),
        ('trailer', '0001_initial'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('device', models.CharField(blank=True, max_length=10, null=True, verbose_name='Device')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Balance')),
                ('lang', models.CharField(choices=[('ru', 'Ru'), ('en', 'En'), ('lv', 'Lv')], default='ru', max_length=50, verbose_name='Language')),
                ('phone_code', models.PositiveSmallIntegerField(verbose_name='Phone code')),
                ('phone', models.PositiveIntegerField(unique=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('email_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Email code')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token')),
                ('code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Code')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='Longitude')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip code')),
                ('reg_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Registration IP')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last IP')),
                ('legal', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('del', 'Del')], max_length=3, null=True, verbose_name='Legal')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Сomments')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.city', verbose_name='City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.country', verbose_name='Country')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.employer', verbose_name='Employer')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', apps.user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('driver_license', models.ImageField(blank=True, null=True, upload_to=apps.user.models.UserDocument.license_front_upload, verbose_name='Driver license')),
                ('driver_license_back', models.ImageField(blank=True, null=True, upload_to=apps.user.models.UserDocument.license_back_upload, verbose_name='Driver license back')),
                ('driver_license_expire', models.DateField(blank=True, null=True, verbose_name='Driver license expire')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to=apps.user.models.UserDocument.selfie_upload, verbose_name='Selfie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User document',
                'verbose_name_plural': 'User documents',
            },
        ),
        migrations.CreateModel(
            name='UserTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('booked_at', models.DateTimeField(verbose_name='Booked at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trailer.trailer', verbose_name='Trailer')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip', verbose_name='Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User trip',
                'verbose_name_plural': 'User trips',
            },
        ),
    ]
