# Generated by Django 5.2.9 on 2025-12-11 16:35

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='invoice_logos/', verbose_name='Logo')),
                ('logo_height_pt', models.PositiveSmallIntegerField(default=95, verbose_name='Logo height in pt')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fax')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('reg', models.CharField(max_length=50, verbose_name='Registration number')),
                ('pvn', models.CharField(max_length=50, verbose_name='PVN')),
                ('bank', models.CharField(max_length=255, verbose_name='Bank')),
                ('swift', models.CharField(max_length=100, verbose_name='SWIFT')),
                ('ibis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ibis')),
                ('warning', models.CharField(blank=True, max_length=255, null=True, verbose_name='Warning')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contact', models.CharField(max_length=255, verbose_name='Contact')),
                ('percent', models.SmallIntegerField(default=0, verbose_name='Percent')),
                ('panel_login', models.CharField(blank=True, max_length=255, null=True, verbose_name='Panel login')),
                ('panel_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Panel password')),
                ('status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('del', 'Del')], default='yes', max_length=3, verbose_name='Activity status')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('short_name', models.CharField(max_length=255, verbose_name='Short name')),
                ('domain', models.CharField(max_length=255, verbose_name='Domain')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone number')),
                ('recaptcha', models.BooleanField(default=False, verbose_name='reCAPTCHA')),
                ('status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('del', 'Del')], default='yes', max_length=3, verbose_name='Activity status')),
                ('initial_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='Initial country')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoice', verbose_name='Invoice')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.owner', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('main', models.ImageField(upload_to=apps.core.models.ProjectImage.image_upload, verbose_name='Main image')),
                ('slider', models.ImageField(upload_to=apps.core.models.ProjectImage.image_upload, verbose_name='Slider image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project image',
                'verbose_name_plural': 'Project images',
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('apple_version', models.CharField(max_length=20, verbose_name='Apple Version')),
                ('android_version', models.CharField(max_length=20, verbose_name='Android Version')),
                ('apple_update_link', models.URLField(verbose_name='Apple update link')),
                ('android_update_link', models.URLField(verbose_name='Android update link')),
                ('test_phones', models.TextField(blank=True, help_text='estnumbers, without +371, separate with "," or ";" or "NEWLINE"', null=True, verbose_name='Test phones')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
            },
        ),
        migrations.CreateModel(
            name='ReferalPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('new', models.PositiveSmallIntegerField(default=0, verbose_name='Percent for newcomers')),
                ('sharing', models.PositiveSmallIntegerField(default=0, verbose_name='Percent for sharing')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project referal percent',
                'verbose_name_plural': 'Project referal procents',
            },
        ),
    ]
